version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: yolo-client:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - my-network
    mem_limit: 512m # increase memory limit to 512mb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yolo-backend:1.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
      - /app/node_modules
    networks:
      - my-network

networks:
  my-network:
    driver: bridge